services:
    sensor_api:
        build: ./sensor_api
        container_name: sensor_api
        ports:
            - "8000:20"

    site_api:
        build: ./site_api
        container_name: site_api
        ports:
            - "8008:20"

    db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: test
        ports:
            - "3306:3306"
        volumes:
            - db-data:/var/lib/mysql

volumes:
    db-data: